# -*- coding: utf-8 -*-
"""Liczba ludności w Polsce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjnCerhfLiYZueRBnR0nGFzVpHvaE8pa
"""

# Instalacja wymaganych pakietów (jeśli nie są zainstalowane)
!pip install pmdarima --quiet
!pip install prophet --quiet

# Import wymaganych bibliotek
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pmdarima import auto_arima
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from prophet import Prophet
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings("ignore")

# Używamy stylu "fivethirtyeight" (który zazwyczaj jest dostępny)
plt.style.use("fivethirtyeight")

# ---------------------------------------
# 1. Przygotowanie danych – dane roczne (ludność Polski w tysiącach) od 1946 do 2024
data = {
    "Year": [
        1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955,
        1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
        1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975,
        1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985,
        1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995,
        1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
        2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
        2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
    ],
    "Population": [
        23640000, 23754000, 24211000, 24613000, 25035000, 25507000, 25999000, 26511000, 27012000, 27550000,
        28080000, 28540000, 29000000, 29479900, 29795200, 30133200, 30483600, 30939700, 31338900, 31551000,
        31810600, 32163300, 32425700, 32670600, 32657711, 32909093, 33202290, 33512156, 33845698, 34184738,
        34527892, 34850228, 35080682, 35413434, 35734868, 36062309, 36398652, 36744964, 37063303, 37340467,
        37571771, 37764318, 37884655, 37988000, 38073000, 38144000, 38203000, 38239000, 38265000, 38284000,
        38294000, 38290000, 38277000, 38263303, 38253955, 38242197, 38218531, 38190608, 38173835, 38157055,
        38125479, 38115641, 38135876, 38167329, 38529866, 38538447, 38533299, 38495659, 38478602, 38437239,
        38432992, 38433558, 38411148, 38382576, 38088564, 37907704, 37766327, 37636508, 37582000
    ]
}

# ---------------------------------------
# 2. Przygotowanie DataFrame
df = pd.DataFrame(data)
df["Date"] = pd.to_datetime(df["Year"].astype(str) + "-01-01")
df.set_index("Date", inplace=True)
df.sort_index(inplace=True)
df.drop(columns=["Year"], inplace=True)
df = df.asfreq("AS")
df["Population"] = df["Population"].interpolate()

print("Dane historyczne (ludność Polski w tys.):")
print(df.head(10))

# ---------------------------------------
# 3. Ustalenie horyzontu prognozy do 2035 r.
last_date = df.index[-1]  # np. 2024-01-01
forecast_horizon = 2035 - last_date.year
print(f"\nPrognozujemy na kolejne {forecast_horizon} lat (do 2035).")
future_dates = pd.date_range(last_date + pd.offsets.YearBegin(1), periods=forecast_horizon, freq="AS")

# ---------------------------------------
# 4. Model ARIMA (auto_arima)
model_arima = auto_arima(
    df["Population"],
    start_p=1, start_q=1,
    max_p=3, max_q=3,
    seasonal=False,  # Dane roczne – brak sezonowości
    d=None,
    trace=False,
    error_action='ignore',
    suppress_warnings=True,
    stepwise=True
)
arima_forecast = model_arima.predict(n_periods=forecast_horizon)
arima_df = pd.DataFrame(arima_forecast, index=future_dates, columns=["ARIMA Forecast"])

# ---------------------------------------
# 5. Model Holt–Winters (Triple Exponential Smoothing)
hw_model = ExponentialSmoothing(df["Population"], trend="add", seasonal=None).fit()
hw_forecast = hw_model.forecast(steps=forecast_horizon)
hw_df = pd.DataFrame(hw_forecast, index=future_dates, columns=["Holt-Winters Forecast"])

# ---------------------------------------
# 6. Model Prophet
prophet_df = df.reset_index().rename(columns={"Date": "ds", "Population": "y"})
prophet_model = Prophet(yearly_seasonality=False)  # Dane roczne – brak dodatkowej sezonowości
prophet_model.fit(prophet_df)
future_prophet = prophet_model.make_future_dataframe(periods=forecast_horizon, freq="YS")
prophet_pred = prophet_model.predict(future_prophet)
prophet_pred_df = prophet_pred.set_index("ds").loc[future_dates, ["yhat"]]
prophet_pred_df.rename(columns={"yhat": "Prophet Forecast"}, inplace=True)

# ---------------------------------------
# 7. Model Regresji Liniowej
df_lr = df.copy().reset_index()
base_year = df_lr["Date"].dt.year.min()
df_lr["Year_Index"] = df_lr["Date"].dt.year - base_year
X = df_lr[["Year_Index"]].values
y = df_lr["Population"].values

lin_reg = LinearRegression()
lin_reg.fit(X, y)

max_index = df_lr["Year_Index"].max()
future_years = np.arange(max_index + 1, max_index + forecast_horizon + 1).reshape(-1, 1)
lr_forecast = lin_reg.predict(future_years)
lr_df = pd.DataFrame(lr_forecast, index=future_dates, columns=["Linear Regression Forecast"])

# ---------------------------------------
# 8. Wizualizacja zbiorcza – wykres z porównaniem modeli
plt.figure(figsize=(14, 8))
plt.plot(df.index, df["Population"], marker="o", label="Dane historyczne", linewidth=2)
plt.plot(arima_df.index, arima_df["ARIMA Forecast"], label="ARIMA Forecast", linestyle="--", color="red", linewidth=2)
plt.plot(hw_df.index, hw_df["Holt-Winters Forecast"], label="Holt-Winters Forecast", linestyle="--", color="green", linewidth=2)
plt.plot(prophet_pred_df.index, prophet_pred_df["Prophet Forecast"], label="Prophet Forecast", linestyle="--", color="blue", linewidth=2)
plt.plot(lr_df.index, lr_df["Linear Regression Forecast"], label="Linear Regression Forecast", linestyle="--", color="purple", linewidth=2)
plt.axvline(x=last_date, color="gray", linestyle="--", linewidth=1.5, label="Koniec danych historycznych")
plt.title("Prognoza liczby ludności w Polsce do 2035 r. – porównanie modeli", fontsize=16)
plt.xlabel("Rok", fontsize=14)
plt.ylabel("Liczba ludności (w tys.)", fontsize=14)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()

# ---------------------------------------
# 9. Wnioski (po polsku)
print("\nWNIOSEK:")
print("Na podstawie rocznych danych z lat 1946–2024, cztery modele (ARIMA, Holt-Winters, Prophet oraz regresja liniowa) "
      "prognozują dalszy spadek liczby ludności Polski do 2035 r. Wyniki poszczególnych modeli są zbliżone, co "
      "potwierdza stabilny trend spadkowy. Prognozy te oparte są wyłącznie na danych historycznych i nie uwzględniają "
      "czynników demograficznych, migracyjnych ani zmian polityk społeczno-ekonomicznych, dlatego wyniki należy traktować orientacyjnie.")